---

- name: Configure Consul service defaults
  become: yes
  template:
    dest: /etc/default/consul
    src: defaults.j2
  notify:
    - restart consul

- name: Create Consul config
  become: yes
  template:
    dest: "{{ consul.directories.config_dir }}/config.json"
    src: config.json.j2
  notify:
    - restart consul

- name: Start Consul service
  become: yes
  service:
    state: started
    name: consul
