---

- name: Install required packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Install Dnsmasq if using as nameserver
  become: yes
  apt:
    name: dnsmasq
    state: present
  when: consul_use_as_nameserver | bool

- name: Create Consul required directories
  become: yes
  file:
    mode: 0755
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ consul_directories_config_dir }}"
    - "{{ consul_directories_data_dir }}"
    - "{{ consul_directories_install_dir }}"
    - "{{ consul_directories_log_dir }}"

- name: Download Consul
  become: yes
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/var/tmp/consul_{{ consul_version }}_linux_amd64.zip"
    sha256sum: "{{ consul_checksum }}"
    validate_certs: "{{ consul_ansible_validate_certs }}"
  register: consul_download_data
  until: consul_download_data | success
  retries: 3
  delay: 10

- name: Extract Consul
  become: yes
  unarchive:
    copy: no
    creates: "{{ consul_directories_install_dir }}/consul"
    dest: "{{ consul_directories_install_dir }}"
    src: "/var/tmp/consul_{{ consul_version }}_linux_amd64.zip"

- name: Link to Consul binary
  become: yes
  file:
    dest: /usr/bin/consul
    mode: 731
    src: "{{ consul_directories_install_dir }}/consul"
    state: link

- name: Install Consul service
  become: yes
  template:
    dest: /etc/init/consul.conf
    mode: 0755
    src: consul.conf.j2

- name: Enable Consul service
  become: yes
  service:
    enabled: yes
    name: consul
