---

- name: Install required packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Download Consul
  become: yes
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul.version }}/consul_{{ consul.version }}_linux_amd64.zip"
    dest: "/usr/local/src/consul_{{ consul.version }}_linux_amd64.zip"

- name: Extract Consul
  become: yes
  unarchive:
    copy: no
    creates: /usr/local/bin/consul
    dest: /usr/local/bin/
    src: "/usr/local/src/consul_{{ consul.version }}_linux_amd64.zip"

- name: Install Consul service
  become: yes
  template:
    dest: /etc/init/consul.conf
    mode: 0755
    src: consul.conf.j2

- name: Enable Consul service
  become: yes
  service:
    enabled: yes
    name: consul

- name: Create Consul required directories
  become: yes
  file:
    mode: 0755
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/consul.d
    - "{{ consul.settings.data_dir }}"
    - "/var/log/consul"
