---

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Install Dnsmasq if using as nameserver
  apt:
    name: dnsmasq
    state: present
  when: consul_use_as_nameserver | bool

- name: Create Consul required directories
  file:
    mode: 0755
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ consul_directories_config_dir }}"
    - "{{ consul_directories_data_dir }}"
    - "{{ consul_directories_install_dir }}"
    - "{{ consul_directories_log_dir }}"

- name: Download Consul
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/var/tmp/consul_{{ consul_version }}_linux_amd64.zip"
    sha256sum: "{{ consul_checksum }}"
    validate_certs: "{{ consul_ansible_validate_certs }}"
  register: consul_download_data
  until: consul_download_data | success
  retries: 3
  delay: 10

- name: Extract Consul
  unarchive:
    copy: no
    creates: "{{ consul_directories_install_dir }}/consul"
    dest: "{{ consul_directories_install_dir }}"
    src: "/var/tmp/consul_{{ consul_version }}_linux_amd64.zip"

- name: Link to Consul binary
  file:
    dest: /usr/bin/consul
    mode: 731
    src: "{{ consul_directories_install_dir }}/consul"
    state: link

- name: Install Consul service for upstart
  template:
    dest: /etc/init/consul.conf
    mode: 0755
    src: consul.service.upstart.j2
  when: ansible_service_mgr == "upstart"

- name: Enable Consul service for upstart
  service:
    enabled: yes
    name: consul
  when: ansible_service_mgr == "upstart"

- name: Install Consul service for systemd
  template:
    dest: /etc/systemd/system/consul.service
    mode: 0755
    src: consul.service.systemd.j2
  when:
    - ansible_service_mgr == "systemd"

- name: Enable Consul service for SystemD
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: consul
  when:
    - ansible_service_mgr == "systemd"
