---

- name: start consul
  become: yes
  service:
    name: consul
    state: started

- name: stop consul
  become: yes
  service:
    name: consul
    state: stopped

- name: reload consul
  become: yes
  service:
    name: consul
    state: reloaded

- name: restart consul
  become: yes
  service:
    name: consul
    state: restarted
