---

- name: start consul
  service:
    name: consul
    state: started

- name: stop consul
  service:
    name: consul
    state: stopped

- name: reload consul
  service:
    name: consul
    state: reloaded

- name: restart consul
  service:
    name: consul
    state: restarted

- name: start dnsmasq
  service:
    name: dnsmasq
    state: started

- name: stop dnsmasq
  service:
    name: dnsmasq
    state: stopped

- name: reload dnsmasq
  service:
    name: dnsmasq
    state: reloaded

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
