#!/bin/bash


function main {
  INSTANCE_REGION=$(curl -s -f http://169.254.169.254/latest/meta-data/placement/availability-zone | sed '$s/.$//')
  if [[ -z ${INSTANCE_REGION} ]]; then
    exit 1
  fi

  local IPS
  IPS=( $( aws ec2 describe-instances \
    --region ${INSTANCE_REGION} \
    --filters Name=tag:Env,Values=prd Name=tag:Role,Values=consul_server Name=instance-state-name,Values=running \
    --output text \
    --query "Reservations[*].Instances[*].PrivateIpAddress") )

  if [ "${#IPS[@]}" -eq 0 ]; then
    exit 1
  fi

  JOIN_STR=$(printf " -join %s" "${IPS[@]}")
  echo "${JOIN_STR}"
}


main "$@"
